FROM jbenet/go-ipfs:latest
MAINTAINER Eris Industries <support@erisindustries.com>

COPY start.sh /usr/local/bin/start.sh

EXPOSE 4001 5001 8080

VOLUME ["/root/.go-ipfs"]

ENTRYPOINT []

CMD ["start.sh"]
